'use client'

import { useEffect, useMemo, useState } from 'react'
import type { User } from '@supabase/supabase-js'
import { createClient } from '@/lib/supabase/client'
import {
  Activity, AlertTriangle, BarChart3, Bell, BrainCircuit, CheckCircle2, ChevronDown, CircleHelp,
  Database, FileBarChart, FileText, GitBranch, Grid2X2, HardDrive, LayoutDashboard, Menu,
  Network, Plus, Search, Settings2, ShieldCheck, Sparkles, Workflow, X, ArrowUpRight,
  RefreshCw, Clock3, SlidersHorizontal, MoreHorizontal, Play, Save, Download, LockKeyhole,
} from 'lucide-react'

const nav = [
  { label: 'Overview', icon: LayoutDashboard },
  { label: 'AI Analyst', icon: BrainCircuit },
  { label: 'Data Sources', icon: Network },
  { label: 'Datasets', icon: Database },
  { label: 'Validation', icon: ShieldCheck, count: '12' },
  { label: 'Insights', icon: Sparkles },
  { label: 'Reports', icon: FileBarChart },
  { label: 'Workflows', icon: Workflow },
  { label: 'Saved Analyses', icon: Save },
]

export default function Home() {
  const [active, setActive] = useState('Overview')
  const [sidebarOpen, setSidebarOpen] = useState(true)
  const [query, setQuery] = useState('')
  const [analystPrompt, setAnalystPrompt] = useState('')
  const [showCommand, setShowCommand] = useState(false)
  const [toast, setToast] = useState('')
  const [transition, setTransition] = useState(false)
  const [user, setUser] = useState<User | null>(null)
  const supabase = useMemo(() => {
    try {
      return createClient()
    } catch {
      return null
    }
  }, [])
  const displayName = user?.user_metadata?.full_name || user?.email?.split('@')[0] || 'Workspace member'
  const initials = displayName.split(/\s+/).map((part: string) => part[0]).join('').slice(0, 2).toUpperCase()

  useEffect(() => {
    if (!supabase) return
    supabase.auth.getUser().then(({ data }) => setUser(data.user))
    const { data: { subscription } } = supabase.auth.onAuthStateChange((_event, session) => setUser(session?.user ?? null))
    return () => subscription.unsubscribe()
  }, [supabase])

  const signOut = async () => {
    if (supabase) await supabase.auth.signOut()
    window.location.assign('/login')
  }

  const filteredNav = useMemo(() => nav.filter((item) => item.label.toLowerCase().includes(query.toLowerCase())), [query])
  const notify = (message: string) => { setToast(message); window.setTimeout(() => setToast(''), 2600) }
  const navigate = (page: string) => { setTransition(true); window.setTimeout(() => { setActive(page); setTransition(false) }, 120) }

  return <main className="cpg-shell">
    <aside className={`cpg-sidebar ${sidebarOpen ? '' : 'is-collapsed'}`}>
      <div className="brand-lockup"><div className="brand-mark"><Sparkles /></div>{sidebarOpen && <div><strong>CPGist</strong><span>AI intelligence</span></div>}</div>
      <div className="workspace-switcher"><div className="workspace-avatar">N</div>{sidebarOpen && <><div className="workspace-copy"><span>Workspace</span><strong>Northstar CPG</strong></div><ChevronDown className="small-icon" /></>}</div>
      <div className="nav-section-label">{sidebarOpen ? 'Workspace' : '•••'}</div>
      <nav className="primary-nav" aria-label="Primary navigation">{nav.map((item) => { const Icon = item.icon; return <button key={item.label} className={`nav-item ${active === item.label ? 'active' : ''}`} onClick={() => navigate(item.label)} title={item.label}><Icon />{sidebarOpen && <span>{item.label}</span>}{sidebarOpen && item.count && <b>{item.count}</b>}</button> })}</nav>
      <div className="sidebar-bottom"><button className="nav-item" onClick={() => notify('Help center opened')}><CircleHelp />{sidebarOpen && <span>Help center</span>}</button><button className="nav-item" onClick={() => navigate('Settings')}><Settings2 />{sidebarOpen && <span>Settings</span>}</button><button className="user-card" onClick={signOut} title="Sign out"><div className="user-avatar">{initials}</div>{sidebarOpen && <div><strong>{displayName}</strong><span>Sign out</span></div>}</button></div>
    </aside>
    <section className="cpg-main">
      <header className="topbar"><button className="icon-button" onClick={() => setSidebarOpen(!sidebarOpen)} aria-label="Toggle navigation"><Menu /></button><button className="global-search" onClick={() => setShowCommand(true)}><Search /><span>Search across your workspace</span><kbd>⌘ K</kbd></button><div className="top-actions"><span className="live-dot"><i /> Live sync</span><button className="icon-button" onClick={() => notify('No new notifications')}><Bell /></button><button className="top-avatar" onClick={signOut} aria-label="Sign out">{initials}</button></div></header>
      <div className={`content-wrap ${transition ? 'page-exit' : 'page-enter'}`}>
        <div className="page-heading"><div><div className="eyebrow">NORTHSTAR CPG / WORKSPACE</div><h1>{active}</h1><p>{descriptions[active] ?? `Explore and manage ${active.toLowerCase()} across your workspace.`}</p></div><div className="heading-actions"><button className="button secondary" onClick={() => notify('Date range selector opened')}>Last 30 days <ChevronDown /></button><button className="button primary" onClick={() => notify('New workflow started')}><Plus /> New workflow</button></div></div>
        {active === 'Overview' && <Overview onNavigate={navigate} onNotify={notify} />}
        {active === 'AI Analyst' && <Analyst prompt={analystPrompt} setPrompt={setAnalystPrompt} onNotify={notify} />}
        {active === 'Data Sources' && <Sources onNotify={notify} />}
        {active === 'Datasets' && <Datasets onNavigate={navigate} onNotify={notify} />}
        {active === 'Validation' && <Quality onNotify={notify} />}
        {active === 'Insights' && <Insights onNavigate={navigate} onNotify={notify} />}
        {active === 'Reports' && <Reports onNotify={notify} />}
        {active === 'Workflows' && <Workflows onNotify={notify} />}
        {active === 'Saved Analyses' && <Saved onNavigate={navigate} />}
        {active === 'Settings' && <Settings />}
      </div>
      {toast && <div className="toast"><CheckCircle2 /> {toast}</div>}
    </section>
    {showCommand && <div className="command-backdrop" onClick={() => setShowCommand(false)}><div className="command-box" onClick={(e) => e.stopPropagation()}><div className="command-input"><Search /><input autoFocus placeholder="Search navigation and datasets..." value={query} onChange={(e) => setQuery(e.target.value)} /><kbd>ESC</kbd></div><div className="command-results">{filteredNav.map((item) => <button key={item.label} onClick={() => { navigate(item.label); setShowCommand(false) }}><item.icon />{item.label}<span>Jump to page</span></button>)}</div></div></div>}
  </main>
}

const descriptions: Record<string, string> = { Overview: 'Your connected intelligence layer for consumer packaged goods.', 'AI Analyst': 'Ask grounded questions across your syndicated intelligence.', 'Data Sources': 'Connect, monitor, and sync the systems behind your analysis.', Datasets: 'Browse the canonical data powering your workspace.', Validation: 'Monitor quality signals before they reach a report.', Insights: 'Signals and opportunities surfaced from your data.', Reports: 'Generated intelligence for every team and decision.', Workflows: 'Automate the path from source file to decision.', 'Saved Analyses': 'Return to questions and answers worth keeping.', Settings: 'Workspace preferences, access, and connected services.' }

function Overview({ onNavigate, onNotify }: { onNavigate: (s: string) => void; onNotify: (s: string) => void }) { return <div className="dashboard-grid"><div className="metric-row"><Metric icon={Database} label="Connected datasets" value="—" delta="Connect a source to begin" /><Metric icon={Activity} label="Data quality score" value="—" delta="Available after ingestion" /><Metric icon={Workflow} label="Active workflows" value="—" delta="No workflows configured" /></div><section className="panel analyst-card"><div className="panel-heading"><div><div className="panel-kicker"><span className="pulse" /> AI ANALYST</div><h2>Ask your intelligence layer</h2><p>Query your syndicated data in plain language.</p></div><button className="text-button" onClick={() => onNavigate('AI Analyst')}>Open analyst <ArrowUpRight /></button></div><div className="suggestion-row"><button onClick={() => onNavigate('AI Analyst')}>Which brands gained share last quarter?</button><button onClick={() => onNavigate('AI Analyst')}>Show me anomalies in retail sales</button><button onClick={() => onNavigate('AI Analyst')}>Summarize my latest reports</button></div></section><section className="panel chart-panel"><PanelHeading kicker="DATA COVERAGE" title="Intelligence coverage" action={<button className="icon-button"><BarChart3 /></button>} /><CoverageChart /></section><section className="panel activity-panel"><PanelHeading kicker="RECENT ACTIVITY" title="Workspace pulse" action={<button className="text-button" onClick={() => onNotify('Activity log opened')}>View all</button>} /><div className="analyst-empty activity-empty"><Activity /><h2>No activity yet</h2><p>Source connections, ingestion jobs, and reports will appear here after real operations run.</p></div></section><section className="panel quality-panel"><PanelHeading kicker="DATA QUALITY" title="Needs your attention" action={<button className="text-button" onClick={() => onNavigate('Validation')}>Review issues</button>} /><div className="quality-score"><div className="score-ring"><strong>94.8</strong><span>/ 100</span></div><div><strong>Healthy workspace</strong><p>12 open issues across 4 datasets</p><div className="progress"><span style={{ width: '82%' }} /></div></div></div></section></div> }
function PanelHeading({ kicker, title, action }: { kicker: string; title: string; action?: React.ReactNode }) { return <div className="panel-heading"><div><div className="panel-kicker">{kicker}</div><h2>{title}</h2></div>{action}</div> }
function Metric({ icon: Icon, label, value, delta, positive }: { icon: React.ElementType; label: string; value: string; delta: string; positive?: boolean }) { return <div className="metric-card"><div className="metric-icon"><Icon /></div><span>{label}</span><strong>{value}</strong><small className={positive ? 'positive' : ''}>{positive ? '↑ ' : ''}{delta}</small></div> }
function ActivityRow({ icon: Icon, title, detail, status, warning }: { icon: React.ElementType; title: string; detail: string; status: string; warning?: boolean }) { return <div className="activity-row"><div className={`activity-icon ${warning ? 'warning' : ''}`}><Icon /></div><div><strong>{title}</strong><span>{detail}</span></div><em className={warning ? 'status-warning' : ''}>{status}</em></div> }
function CoverageChart() { return <div className="analyst-empty"><Database /><h2>No coverage data yet</h2><p>Coverage trends will appear after a source is connected and its first dataset is ingested.</p></div> }
function Analyst({ prompt, setPrompt, onNotify }: { prompt: string; setPrompt: (s: string) => void; onNotify: (s: string) => void }) { const [answer, setAnswer] = useState(''); const [loading, setLoading] = useState(false); const [lines, setLines] = useState<string[]>([]); const ask = async () => { if (!prompt.trim() || loading) return; setLoading(true); setLines(['> submitting analyst request']); try { const response = await fetch('/api/analyst', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ prompt }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setLines((data.trace ?? []).map((line: string) => `> ${line.toLowerCase()}`)); setAnswer(data.answer); setPrompt('') } catch (error) { onNotify(error instanceof Error ? error.message : 'The analyst is temporarily unavailable.') } finally { setLoading(false) } }; return <section className="analyst-workspace"><div className="terminal-header"><span className="terminal-dot" /><span>CPGist Analyst / grounded mode</span><span className="terminal-status">● {loading ? 'THINKING' : 'READY'}</span></div><div className="analyst-body">{loading && <div className="tool-terminal">{lines.map((line) => <div key={line}>{line}<span> done</span></div>)}<div className="cursor-line">_</div></div>}{answer && !loading ? <div className="answer"><div className="answer-label">ANALYSIS COMPLETE <span>· Ollama response</span></div><p>{answer}</p><div className="citation"><Database /> Source context <span>Connected workspace datasets</span></div><div className="answer-actions"><button className="button secondary" onClick={() => onNotify('Report export queued')}><Download /> Export report</button><button className="button secondary" onClick={() => onNotify('Analysis shared')}>Share insight</button></div></div> : !loading && <div className="analyst-empty"><Sparkles /><h2>What would you like to know?</h2><p>Ask a question about your connected CPG data. The analyst will show its sources and reasoning.</p></div>}<div className="prompt-box"><textarea value={prompt} onChange={(e) => setPrompt(e.target.value)} onKeyDown={(e) => { if (e.key === 'Enter' && !e.shiftKey && !e.nativeEvent.isComposing && e.keyCode !== 229) { e.preventDefault(); ask() } }} placeholder="Ask about your data..." /><button className="send-button" onClick={ask} disabled={loading}><Play /></button></div><div className="prompt-hints"><button onClick={() => setPrompt('Which brands gained share last quarter?')}>Share by brand</button><button onClick={() => setPrompt('Find anomalies in retail sales')}>Find anomalies</button><button onClick={() => setPrompt('Summarize the latest reports')}>Summarize reports</button></div></div></section> }
function Sources({ onNotify }: { onNotify: (s: string) => void }) { return <div className="sources-grid"><SourceCard icon={GitBranch} name="GitHub Syndicate" type="Repository" status="Not configured" detail="Repository connection required" onNotify={onNotify} actionLabel="Configure connection" /><SourceCard icon={HardDrive} name="Google Drive" type="Cloud storage" status="Not configured" detail="OAuth credentials are checked server-side before connection" onNotify={onNotify} actionLabel="Connect Google Drive" href="/api/connectors/google" /><SourceCard icon={Network} name="Microsoft Graph" type="Enterprise data" status="Not configured" detail="OAuth credentials are checked server-side before connection" onNotify={onNotify} actionLabel="Connect Microsoft Graph" href="/api/connectors/microsoft" /></div> }
function SourceCard({ icon: Icon, name, type, status, detail, action, href, onNotify, actionLabel }: any) { return <section className="panel source-card"><div className="source-icon"><Icon /></div><div className="source-title"><h2>{name}</h2><span>{type}</span></div><div className={`source-status ${status === 'Connected' ? 'connected' : 'not-configured'}`}><i /> {status}</div><p>{detail}</p>{href ? <a className="button secondary full" href={href}>{status === 'Connected' ? <><RefreshCw /> {actionLabel}</> : actionLabel}</a> : <button className="button secondary full" onClick={action ?? (() => onNotify?.('This connector is not configured.'))}>{status === 'Connected' ? <><RefreshCw /> {actionLabel}</> : <>Configure connection</>}</button>}</section> }
function Datasets({ onNavigate, onNotify }: any) { const data = [{ name: 'Brand Master', rows: '18,420', updated: '12 min ago', quality: '98.4%' }, { name: 'Retail Sales Q3', rows: '2.4M', updated: '1 hr ago', quality: '91.2%' }, { name: 'Media Performance', rows: '842K', updated: '4 days ago', quality: '89.6%' }, { name: 'Category Taxonomy', rows: '3,208', updated: 'Yesterday', quality: '99.1%' }]; return <div className="dataset-layout"><section className="panel data-table"><div className="table-toolbar"><div><div className="panel-kicker">CANONICAL DATASETS</div><h2>All datasets <span>24</span></h2></div><div className="toolbar-actions"><button className="button secondary" onClick={() => onNotify('Filters opened')}><SlidersHorizontal /> Filter</button><button className="button primary" onClick={() => onNotify('Dataset import started')}><Plus /> Import dataset</button></div></div><div className="table-head"><span>Dataset</span><span>Rows</span><span>Last updated</span><span>Quality</span><span /></div>{data.map((item) => <button className="dataset-row" key={item.name} onClick={() => onNotify(`${item.name} detail opened`)}><strong><Database />{item.name}</strong><span>{item.rows}</span><span><Clock3 />{item.updated}</span><span className="quality-good">{item.quality}</span><MoreHorizontal /></button>)}</section><section className="panel dataset-side"><div className="panel-kicker">INGESTION PIPELINE</div><h2>From source to signal</h2><div className="pipeline">{['NEW FILE','PROFILE','VALIDATE','NORMALIZE','ANALYZE'].map((step, i) => <div className={i < 3 ? 'done' : ''} key={step}><i>{i < 3 ? <CheckCircle2 /> : i + 1}</i><span>{step}</span></div>)}</div><button className="button secondary full" onClick={() => onNavigate('Workflows')}>View workflows <ArrowUpRight /></button></section></div> }
function Quality({ onNotify }: any) { return <div className="quality-layout"><section className="panel issue-table"><PanelHeading kicker="VALIDATION QUEUE" title="Open issues" action={<button className="button secondary" onClick={() => onNotify('Validation requires an ingested dataset')}><Activity /> Run scan</button>} /><div className="analyst-empty"><ShieldCheck /><h2>No validation results yet</h2><p>Connect a source and complete ingestion before validation can inspect real rows.</p></div></section><section className="panel quality-summary"><div className="panel-kicker">QUALITY TREND</div><div className="big-score">—<span>/100</span></div><p>Available after dataset ingestion</p><div className="summary-note"><ShieldCheck /> No quality score calculated</div></section></div> }
function Insights({ onNavigate, onNotify }: any) { return <div className="insight-grid">{[{ title: 'Private label is gaining share', text: 'Value-tier brands grew 2.1 points in grocery over the last quarter.', tag: 'Opportunity', color: 'green' }, { title: 'Media efficiency dipped', text: 'Paid social ROAS fell below the category benchmark in three regions.', tag: 'Watch', color: 'amber' }, { title: 'Premium is resilient', text: 'Premium households continue to trade up despite volume pressure.', tag: 'Signal', color: 'cyan' }].map((insight) => <section className="panel insight-card" key={insight.title}><div className={`insight-tag ${insight.color}`}>{insight.tag}</div><h2>{insight.title}</h2><p>{insight.text}</p><div className="insight-footer"><span><Sparkles /> AI surfaced</span><button className="text-button" onClick={() => { onNotify('Investigation context prepared'); onNavigate('AI Analyst') }}>Investigate <ArrowUpRight /></button></div></section>)}</div> }
function Reports({ onNotify }: any) { return <div className="report-list"><div className="section-actions"><div><div className="panel-kicker">REPORT LIBRARY</div><h2>Generated intelligence</h2></div><button className="button primary" onClick={() => onNotify('Report generation queued')}><Plus /> Generate report</button></div>{['Q3 Category Performance Report', 'Brand Health Executive Brief', 'Retail Media Readout'].map((name, i) => <section className="panel report-row" key={name}><div className="report-icon"><FileText /></div><div><strong>{name}</strong><span>Generated {i + 1} day{i ? 's' : ''} ago · AI Analyst</span></div><em>Ready</em><button className="icon-button" onClick={() => onNotify('Report options opened')}><MoreHorizontal /></button></section>)}</div> }
function Workflows({ onNotify }: any) { return <div className="workflow-layout"><section className="panel workflow-card"><div className="section-actions"><div><div className="panel-kicker">AUTOMATION GRAPH</div><h2>Dataset intelligence flow</h2></div><button className="button primary" onClick={() => onNotify('Workflow run requested')}><Play /> Run workflow</button></div><div className="workflow-steps">{['NEW FILE','PROFILE','VALIDATE','NORMALIZE','ANALYZE','REPORT','NOTIFY'].map((step, i) => <div className={i < 4 ? 'workflow-step complete' : i === 4 ? 'workflow-step current' : 'workflow-step'} key={step}><div className="step-node">{i < 4 ? <CheckCircle2 /> : i + 1}</div><span>{step}</span>{i < 6 && <i />}</div>)}</div></section><section className="panel run-card"><div className="panel-kicker">LATEST RUN</div><h2>Retail Sales Q3</h2><p><span className="connected-dot" /> Running validation stage</p><div className="progress"><span style={{ width: '58%' }} /></div><small>4 of 7 steps complete</small></section></div> }
function Saved({ onNavigate }: any) { return <div className="saved-grid">{['Which brands gained share last quarter?', 'Retail sales anomaly scan', 'Q3 category narrative'].map((name, i) => <button className="panel saved-card" key={name} onClick={() => onNavigate('AI Analyst')}><div className="saved-top"><Save /><span>{i + 1} day{i ? 's' : ''} ago</span></div><h2>{name}</h2><p>AI Analyst · grounded in connected workspace datasets</p><ArrowUpRight /></button>)}</div> }
function Settings() { return <div className="settings-layout"><section className="panel settings-nav"><button className="active">Workspace</button><button>Members & access</button><button>Notifications</button><button>Integrations</button></section><section className="panel settings-content"><div className="panel-kicker">WORKSPACE SETTINGS</div><h2>Northstar CPG</h2><div className="settings-field"><label>Workspace name</label><input value="Northstar CPG" readOnly /></div><div className="settings-field"><label>Workspace ID</label><div className="locked-input"><LockKeyhole /> northstar-cpg-prod</div></div><button className="button primary">Save changes</button></section></div> }
